### ISSUE TITLE
关于链接的一些细节问题

### ISSUE THREAD

**Issue by fangjue** [uestc-bbs-new/qshp-fe#31]
1. 使用 `utils/siteRoot` 而不要硬编码 `bbs.uestc.edu.cn`，方便在不同的环境下开发与测试。本地开发时 `siteRoot` 指向 `https://bbs.uestc.edu.cn`，将直接从现在正在运行的河畔服务器上获取头像、附件、表情等各类资源，点击回到旧版时也会回到现在的河畔。编译发布到测试服务器上时，`siteRoot` 为空，指向测试服务器所在主机，点击回到旧版时跳转到测试服务器上的旧版河畔，而不会进入 bbs.uestc.edu.cn；未来正式上线时也不会因为域名的改变而产生其他意料之外的问题。
```
import siteRoot from '@/utils/siteRoot'
let avatarUrl = `${siteRoot}/uc_server/...` // 注意 siteRoot 末尾不带斜杠，使用时需要在后面加上斜杠。
```

2. 不在 SPA 路由范围内的“外部”链接，例如旧版河畔的链接以及可能的站外链接，请在使用 `<Link>` 组件时增加 external 属性，否则会经过 React 路由而出现 404 错误。例如：
```<Link to={`${siteRoot`}/forum.php`} external>旧版河畔首页</Link>```

3. 一般地，避免使用 `onClick={_ => location.href = 'xxx'}`，而应该正确使用 `<Link>` 组件，体现出正确的链接语义，使用户能正常复制、中键/Ctrl+单击/右键新窗口打开链接。

**Comment by danolphoenix** [comment]
围观一下新版
