### ISSUE TITLE
关于回复按钮的跳转

### ISSUE THREAD

**Issue by CuiaCuiSha** [uestc-bbs-new/qshp-fe#34]
均是点击“回复”按钮后的反馈，主要包括三点。

1. 网页滚动至最下方的问题
点击击回复按钮后，编辑器中虽然出现了引用内容，但网页不会滚动至最下方。（神奇的是，点击自己发表的楼层的“回复按钮”，页面就会滚动到最下方。）

2. 编辑器光标顺序
点击击回复按钮后，编辑器中虽然出现了引用内容，但光标位置默认出现在引用文本的前方。
建议光标位置为最后？

3. 回复的贴子涉及回复，排版有bug
描述起来有些困难，测试以下就知道咧。
http://222.197.183.89:65342/thread/2101055?page=1#vditor

**Comment by fangjue** [comment]
1、2 已修复，3 涉及到如何提取引用内容，例如最多几行，最多多少字，还要去除回复中原本的引用，有待进一步研究。

还有回复对话框也要实现，不然不方便边看内容边回复；还可以考虑做一个引用全部内容”逐句回复“的功能。（某人体 [s:74]）

**Comment by CuiaCuiSha** [comment]
你好厉害啊。我在想我除了提issue，还能做些什么呢，比如如何从零开始学会看懂河畔的代码。

新的发现：
点击回复a贴后，不操作。切换其他贴子，编辑器内仍是a贴内容，换衣是和缓存有关？

**Comment by fangjue** [comment]
这是 Vditor 默认的自动保存功能，目前暂时维持现状，后续考虑做一个本地草稿箱的功能？（现在的“保存草稿”我觉得也要，因为涉及附件的帖子草稿保存在服务器上比较方便，本地草稿用于短期存放，防止不小心关闭窗口丢失数据？）

关于前一个问题，我等会儿去隔壁水一帖。

**Comment by fangjue** [comment]
e18f0ee 初步实现了正确的引用内容提取，3 也修复了。等到下一次版本发布就能看到了。
