### ISSUE TITLE
密语区bug

### ISSUE THREAD

**Issue by CuiaCuiSha** [uestc-bbs-new/qshp-fe#35]
鼠标移动到用户头像，就可以看到注册时间、在线时长。
切换非管理账号后仍存在此问题。

<img width="306" alt="Snipaste_2023-12-20_21-37-56" src="https://github.com/uestc-bbs-new/qshp-fe/assets/32769735/550324e2-f359-493c-acc0-9d89723bf251">

**Comment by fangjue** [comment]
因为我还没来得及处理 https://github.com/uestc-bbs-new/bbs/blob/main/app-view/view_daos/view_mysql_daos/PostDao.go#L22 中的一团混乱，不过考虑到信息泄漏，先紧急处理一下。
