### ISSUE TITLE
点击回复按钮太多次的话会回复很多遍

### ISSUE THREAD

**Issue by Muse-SAMA** [uestc-bbs-new/qshp-fe#38]
http://222.197.183.89:65342/thread/2101055?page=1
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/120369081/40c93595-fb01-43d8-a1f5-d108fa76f7c6)
要不然在多次点击回复帖子的时候加个“已回复，请耐心等待“的提示框，不然多次点击就会出现同时回复很多次的情况，还是因为我这里太卡了？

**Comment by fangjue** [comment]
在 #36 重构与整合的过程中修复了这个问题，等明天或后天发布下一个版本。
