### ISSUE TITLE
回复的弹出窗口中，全屏按钮无效

### ISSUE THREAD

**Issue by CuiaCuiSha** [uestc-bbs-new/qshp-fe#40]
点击回复，出现图1。

如果我想长篇大论回复，点击全屏，出现图2。

全屏后更加mini了┭┮﹏┭┮

<img width="745" alt="1" src="https://github.com/uestc-bbs-new/qshp-fe/assets/32769735/0329c27e-18b3-4d96-843f-3cc68d3e6ded">
<img width="846" alt="2" src="https://github.com/uestc-bbs-new/qshp-fe/assets/32769735/b8e12728-2b97-4d5c-a0b8-cdf94df92cf7">

**Comment by fangjue** [comment]
这个问题拖了好长时间了。一开始我在想要不要有个单独的回复页面，后来觉得没必要，单独的回复页面失去了“上下文”，在现有的回复对话框里自由切换全屏才是更好的体验。

后来重构了帖子中弹出的对话框（特别是以后还会有更多其他对话框，例如评分、管理操作等等），又是一个大 patch（ bc9db56 ）。今晚考虑了下要不要魔改 Vditor，结果发现 CSS :has 就行了，只是旧的浏览器不支持，后面再考虑用 MutationObserver 兼容或者还是得在 Vditor 里增加全屏状态的事件。
