### ISSUE TITLE
关于深色模式的几个问题

### ISSUE THREAD

**Issue by Jasoncikky** [uestc-bbs-new/qshp-fe#42]
新河畔加入了暗黑模式，可将网页外观转为深色，是很人性化的一个功能，但在细节上还有一些问题。

## 1.暗黑模式的部分不连续性
如果采用前进、后退、本标签页打开可以保留暗黑模式状态，但新标签页/新窗口打开则不会，需要手动切换。
如果能识别浏览器本身的深色模式设置自适应效果就更好了（如[少数派](https://sspai.com/)）。

## 2.名称修改建议
现行名称为“暗黑模式”与“light模式”，中英文混杂很奇怪。
我的建议是改为“深色模式”与“浅色模式”，这个称呼也更通用一些。

### 网页外观
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92702549/d29493d6-6694-4462-b192-8c5e2bc14fc8)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92702549/7e8f210f-90b2-4c52-96f3-ecbd27e91105)
该处文字有反色，但背景没有（均采用了渐变色）。
### 帖子内部
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92702549/5f5531d3-8979-4169-b00d-22f4ff2ce12a)
该处标签文字应当反色（变为白色），背景可以不变。
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92702549/7c92928e-b3a7-42de-b784-4a3c5c6e6eee)
包括这里的标签
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92702549/90a7ca17-da07-4ead-9562-59c8c29fe236)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/92702549/22786fb9-4607-499a-b015-288346f16a16)
回复引用的部分文字进行了反色处理，但背景并没有（我用拾色器检查了）。

**Comment by fangjue** [comment]
暗色模式问题很多的，先解决 1、2，3 先解决除帖子内容外已发现的颜色问题。

帖子内容的暗色模式比较复杂，特别是用户还能自定义文字颜色，需要在渲染时对颜色做一些处理（包括颜色处理的算法也不简单）并在模式切换时更换颜色。

**Comment by fangjue** [comment]
跟随系统与手动切换模式之间的冲突，你怎么看？

跟随系统设置，如果系统设置改变，河畔的颜色模式要不要跟着改变呢？

用户手动设置模式以后，系统设置又改变了，这时候按照哪一种？还是明确区分“浅色”、“深色”、“跟随系统”三种模式？

**Comment by fangjue** [comment]
@Muse-SAMA 在设计时也可以考虑一下深色模式。

**Comment by Jasoncikky** [comment]
> 暗色模式问题很多的，先解决 1、2，3 先解决除帖子内容外已发现的颜色问题。
> 
> 帖子内容的暗色模式比较复杂，特别是用户还能自定义文字颜色，需要在渲染时对颜色做一些处理（包括颜色处理的算法也不简单）并在模式切换时更换颜色。

这点是最蛋疼的，尤其是我看了很多版块的版头，全都是#ff0000的大红色，深色模式下文字可读性会下降很多。

**Comment by fangjue** [comment]
这些问题基本解决了，有些地方的颜色我选得不一定合适，你们帮忙看看。（例如首页最新发表的渐变和版块公告顶部的渐变，灰色好看还是蓝色好看？蓝色的色调和亮度合适吗？）

@Jasoncikky @Muse-SAMA

**Comment by Muse-SAMA** [comment]
@fangjue 我觉得现在这个暗色模式能满足需求了。其他具体需要完善细节的处理正在进行设计，现在完成了几个页面，我们尽快整理出深色模式转换的颜色标准文档。

**Comment by Muse-SAMA** [comment]
@fangjue 不过我有个问题，就是代码块的颜色显示这个需要我们设计吗？还是用现成的风格就好了？

**Comment by fangjue** [comment]
> @fangjue 不过我有个问题，就是代码块的颜色显示这个需要我们设计吗？还是用现成的风格就好了？有哪里能看Markdown代码显示风格的地方吗？

代码块的颜色具体指什么？编辑器里的 Markdown 源代码，还是帖子中内嵌的代码块渲染出来的样式？哦，看了上面的文档，指的是后者，推荐一个稍微深一点的背景色就好？代码高亮是 Vditor 内部调用 hljs，目前先不动吧。

“消息界面的超链接”，这一块我后面会修复，不用另外设计（这里的超链接与其他地方的用户名超链接、帖子内容中的超链接相比并没有什么特殊性，CSS 里设置好颜色就行了）

帖子高亮在 Discuz! 中是固定的 9 种颜色（ https://github.com/uestc-bbs-new/bbs/blob/main/forum/ThreadDao.go#L64 ），如果有时间的话可以分别选取暗色模式下对应的颜色，不然按照帖子内容的颜色处理算法（用户可以任意设置字体颜色，现在只是个初步实现，还需优化调整；如果有了这九种颜色对应的“亮色”，也可作为优化该算法的基准以供参考）来也行。

```go
item.HighlightColor = map[int8]string{
  0: "",
  1: "#EE1B2E",
  2: "#EE5023",
  3: "#996600",
  4: "#3C9D40",
  5: "#2897C5",
  6: "#2B65B7",
  7: "#8F2A90",
  8: "#EC1282",
  9: "",
}[item.Highlight%10]
```

**Comment by Jasoncikky** [comment]
> > @fangjue 不过我有个问题，就是代码块的颜色显示这个需要我们设计吗？还是用现成的风格就好了？有哪里能看Markdown代码显示风格的地方吗？
> 
> 代码块的颜色具体指什么？编辑器里的 Markdown 源代码，还是帖子中内嵌的代码块渲染出来的样式？哦，看了上面的文档，指的是后者，推荐一个稍微深一点的背景色就好？代码高亮是 Vditor 内部调用 hljs，目前先不动吧。
> 
> “消息界面的超链接”，这一块我后面会修复，不用另外设计（这里的超链接与其他地方的用户名超链接、帖子内容中的超链接相比并没有什么特殊性，CSS 里设置好颜色就行了）
> 
> 帖子高亮在 Discuz! 中是固定的 9 种颜色（ https://github.com/uestc-bbs-new/bbs/blob/main/forum/ThreadDao.go#L64 ），如果有时间的话可以分别选取暗色模式下对应的颜色，不然按照帖子内容的颜色处理算法（用户可以任意设置字体颜色，现在只是个初步实现，还需优化调整；如果有了这九种颜色对应的“亮色”，也可作为优化该算法的基准以供参考）来也行。
> 
> ```go
> item.HighlightColor = map[int8]string{
>   0: "",
>   1: "#EE1B2E",
>   2: "#EE5023",
>   3: "#996600",
>   4: "#3C9D40",
>   5: "#2897C5",
>   6: "#2B65B7",
>   7: "#8F2A90",
>   8: "#EC1282",
>   9: "",
> }[item.Highlight%10]
> ```

高亮除了这几种文字颜色外还有背景色，但是背景色可选的就多了（理论上所有16进制颜色代码都可以），这个要考虑在内吗？如果实现较难可以尽量避免使用。

**Comment by fangjue** [comment]
> > > @fangjue 不过我有个问题，就是代码块的颜色显示这个需要我们设计吗？还是用现成的风格就好了？有哪里能看Markdown代码显示风格的地方吗？
> > 
> > 
> > 代码块的颜色具体指什么？编辑器里的 Markdown 源代码，还是帖子中内嵌的代码块渲染出来的样式？哦，看了上面的文档，指的是后者，推荐一个稍微深一点的背景色就好？代码高亮是 Vditor 内部调用 hljs，目前先不动吧。
> > “消息界面的超链接”，这一块我后面会修复，不用另外设计（这里的超链接与其他地方的用户名超链接、帖子内容中的超链接相比并没有什么特殊性，CSS 里设置好颜色就行了）
> > 帖子高亮在 Discuz! 中是固定的 9 种颜色（ https://github.com/uestc-bbs-new/bbs/blob/main/forum/ThreadDao.go#L64 ），如果有时间的话可以分别选取暗色模式下对应的颜色，不然按照帖子内容的颜色处理算法（用户可以任意设置字体颜色，现在只是个初步实现，还需优化调整；如果有了这九种颜色对应的“亮色”，也可作为优化该算法的基准以供参考）来也行。
> > ```go
> > item.HighlightColor = map[int8]string{
> >   0: "",
> >   1: "#EE1B2E",
> >   2: "#EE5023",
> >   3: "#996600",
> >   4: "#3C9D40",
> >   5: "#2897C5",
> >   6: "#2B65B7",
> >   7: "#8F2A90",
> >   8: "#EC1282",
> >   9: "",
> > }[item.Highlight%10]
> > ```
> 
> 高亮除了这几种文字颜色外还有背景色，但是背景色可选的就多了（理论上所有16进制颜色代码都可以），这个要考虑在内吗？如果实现较难可以尽量避免使用。

目前不处理背景色，后面再考虑。

总的来说，“用户生成内容”的暗色适配是比较复杂的，而且我都没找到现成的解决方案，可能其他平台直接就不支持自定义颜色？但是我并不希望河畔失去这个能力。

**Comment by Muse-SAMA** [comment]
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/120369081/efdd9a35-9c36-4bdd-be39-4cfca2cfccf3)
@fangjue 对深色模式整理了一份标准，上面的数字是rgb，已经更新到3.1中了

**Comment by Muse-SAMA** [comment]
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/120369081/ad4b8fc6-8caa-475b-88f6-7059e4617c9d)
首页渐变色修改如上

**Comment by Muse-SAMA** [comment]
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/120369081/6961b5bb-b4ec-4d96-a054-69697ff7abfb)
暗黑模式板块的版头渐变色也可以改成和首页渐变色的一致

**Comment by Muse-SAMA** [comment]
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/120369081/3ace0d7d-66b1-4528-b7d5-f01fc96c1ee4)
![image](https://github.com/uestc-bbs-new/qshp-fe/assets/120369081/1ac5c6fc-e9fc-4e01-a757-d2761f1ded23)
暗黑模式下点击回复的时候显示的回复的话颜色显示不太对劲，和楼里回复的话显示的一样就好了。

**Comment by fangjue** [comment]
> ![image](https://private-user-images.githubusercontent.com/120369081/302267803-3ace0d7d-66b1-4528-b7d5-f01fc96c1ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzI5MjIsIm5iZiI6MTcwNzEzMjYyMiwicGF0aCI6Ii8xMjAzNjkwODEvMzAyMjY3ODAzLTNhY2UwZDdkLTY2YjEtNDUyOC1iN2Q1LWYwMWZjOTZjMWVlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMTMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDdmMGFlNGMzY2M0ZmIxMmI0ODdhMmE0Mjc0OWExMzY3NzVkYzI5NDE3NGY0NTExMzliMGQwZDMzMGNlNjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OYYXHPamWa9lHz2kwRVMTzvGJifglIK7lrwoezvMHjc) ![image](https://private-user-images.githubusercontent.com/120369081/302267888-1ac5c6fc-e9fc-4e01-a757-d2761f1ded23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzI5MjIsIm5iZiI6MTcwNzEzMjYyMiwicGF0aCI6Ii8xMjAzNjkwODEvMzAyMjY3ODg4LTFhYzVjNmZjLWU5ZmMtNGUwMS1hNzU3LWQyNzYxZjFkZWQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMTMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBkNjViYTBjMWY0MDU0N2ZhZWIzNDkzYWU2YzI2ZWRiMTJlZGVhNzIwNjkzODBkNzljN2EzYTYxOWMxMDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XcKTpgDuWShu43Qlc3dDPEbGt-DJBB_3YSda1k9loWw) 暗黑模式下点击回复的时候显示的回复的话颜色显示不太对劲，和楼里回复的话显示的一样就好了。

分别在 51d3194f369e3c06793e3d667cf63512d3af5a47 与 d44de44b0bc705ff1c2931ca5bbc37bba190677f 中修复（暂未上线）。

**Comment by fangjue** [comment]
上线后似乎暂未收到有关暗色模式的问题？总体上基本可用，因此关闭。后续发现其他问题可以单独提出。
