### ISSUE TITLE
建议对需要新增、修复等功能点进行拆分，然后放在 issue 里，每个人自行领取，不然工作可能产生冲突

### ISSUE THREAD

**Issue by gitguoxiangyu** [uestc-bbs-new/qshp-fe#44]

**Comment by gitguoxiangyu** [comment]
而且工作内容也没有明确指向，有点不知道要干嘛

**Comment by fangjue** [comment]
这个问题提得很好，一开始我也是这样的想法，只是后来看到大家的积极性不高，再加上河畔需求与功能的复杂性，一直没有仔细整理。上周就有计划提一些 issue，但因为上班太忙进展不大。现在先初步提了几个，欢迎选择感兴趣的方面并提交代码，有任何问题随时提出。

已邀请加入 uestc-bbs-new 组织，加入后应该有 Triage 的权限，可以在 Issue 中把自己添加到 Asignees 中。
