### ISSUE TITLE
搜索bug

### ISSUE THREAD

**Issue by Muse-SAMA** [uestc-bbs-new/qshp-fe#67]
目前初步测试了一下搜索界面，发现了三个问题：
1. 搜索栏有时候会显示【更多用户】，有时候不会，有时候是用户和帖子混合显示的，uid的匹配是否放在下面用户的分组里更好？
![image](https://github.com/uestc-bbs-new/bbs/assets/120369081/72119ef6-a8d7-421a-9b10-97b0fd74140f)
2. 如果在搜索栏搜索时先点击【更多帖子】，再在结果页面的搜索栏继续点击【更多用户】，会出现似乎是最新发帖的结果列表？
![image](https://github.com/uestc-bbs-new/bbs/assets/120369081/ee165b0e-b2c3-4d5b-aba2-c716932b7476)
3. 如果在搜索栏搜索时先点击【更多用户】，再点击【更多帖子】，会没有任何反应

**Comment by fangjue** [comment]
没有更多用户，是因为搜索结果里就没有。

输入纯数字时，搜索 uid/tid 的可能性更大，真正与内容相关的纯数字关键词可能并不多（或者也可以考虑把这一部分单独做个例外？），所以才这么安排顺序的。

2、3 是因为搜索结果页面的重构还未完成，以后搜索帖子和搜索用户会有单独的网址，不像之前那样混在一起。

**Comment by fangjue** [comment]
基本解决。
